/**
 * Parking and for-sale infrastructure.
 *
 * Nameserver detection is more reliable than page-content detection, because a parked domain must
 * delegate DNS to the parking operator, whereas a parking page's HTML changes constantly and is often
 * served through a redirect chain the probe may not follow.
 */
export const PARKING_NAMESERVERS: readonly { pattern: string; provider: string }[] = [
  { pattern: 'sedoparking.com', provider: 'Sedo' },
  { pattern: 'parkingcrew.net', provider: 'ParkingCrew' },
  { pattern: 'bodis.com', provider: 'Bodis' },
  { pattern: 'above.com', provider: 'Above.com' },
  { pattern: 'afternic.com', provider: 'Afternic' },
  { pattern: 'dan.com', provider: 'Dan.com' },
  { pattern: 'undeveloped.com', provider: 'Undeveloped' },
  { pattern: 'namebrightdns.com', provider: 'NameBright' },
  { pattern: 'dsredirection.com', provider: 'DomainSpot' },
  { pattern: 'domaincontrol.com.parked', provider: 'GoDaddy parked' },
  { pattern: 'parktons.com', provider: 'Parktons' },
  { pattern: 'parklogic.com', provider: 'ParkLogic' },
  { pattern: 'cashparking.com', provider: 'GoDaddy CashParking' },
  { pattern: 'domainparkingserver.net', provider: 'Domain Parking Server' },
  { pattern: 'parkpage.foundationapi.com', provider: 'Network Solutions parking' },
  { pattern: 'fabulous.com', provider: 'Fabulous' },
  { pattern: 'domainmarket.com', provider: 'DomainMarket' },
  { pattern: 'hugedomains.com', provider: 'HugeDomains' },
  { pattern: 'buydomains.com', provider: 'BuyDomains' },
  { pattern: 'parkingpage.namecheap.com', provider: 'Namecheap parking' },
  { pattern: 'registrar-servers.com.park', provider: 'Namecheap parking' },
  { pattern: 'sav.com', provider: 'Sav' },
  { pattern: 'brainydns.com', provider: 'Brainy DNS parking' },
  { pattern: 'nsone.net.parked', provider: 'NS1 parked' },
];

/**
 * Body fingerprints for parking pages, used when the nameservers are inconclusive. Matched
 * case-insensitively against the fetched HTML.
 */
export const PARKING_BODY_FINGERPRINTS: readonly string[] = [
  'this domain is for sale',
  'this domain name is for sale',
  'buy this domain',
  'domain is parked',
  'parked free, courtesy of',
  'the domain you are looking for is for sale',
  'inquire about this domain',
  'make an offer',
  'domain for sale',
  'this webpage was generated by the domain owner using sedo',
  'sedo domain parking',
  'parkingcrew',
  'future home of something quite cool',
  'coming soon',
  'website coming soon',
  'under construction',
  'default web site page',
  'welcome to nginx',
  'apache2 ubuntu default page',
  'it works!',
  'index of /',
  'domain default page',
  'this site is temporarily unavailable',
  'account suspended',
  'suspended page',
  'plesk default page',
  'cpanel default page',
  'hostinger parking',
  'this domain has been registered',
];
