import { isAtOrUnder } from '../hostname';

/**
 * Parking and for-sale infrastructure.
 *
 * Nameserver detection is more reliable than page-content detection, because a parked domain must
 * delegate DNS to the parking operator, whereas a parking page's HTML changes constantly and is often
 * served through a redirect chain the probe may not follow.
 */
export const PARKING_NAMESERVERS: readonly { pattern: string; provider: string }[] = [
  { pattern: 'sedoparking.com', provider: 'Sedo' },
  { pattern: 'parkingcrew.net', provider: 'ParkingCrew' },
  { pattern: 'bodis.com', provider: 'Bodis' },
  { pattern: 'above.com', provider: 'Above.com' },
  { pattern: 'afternic.com', provider: 'Afternic' },
  { pattern: 'dan.com', provider: 'Dan.com' },
  { pattern: 'undeveloped.com', provider: 'Undeveloped' },
  { pattern: 'namebrightdns.com', provider: 'NameBright' },
  { pattern: 'dsredirection.com', provider: 'DomainSpot' },
  { pattern: 'domaincontrol.com.parked', provider: 'GoDaddy parked' },
  { pattern: 'parktons.com', provider: 'Parktons' },
  { pattern: 'parklogic.com', provider: 'ParkLogic' },
  { pattern: 'cashparking.com', provider: 'GoDaddy CashParking' },
  { pattern: 'domainparkingserver.net', provider: 'Domain Parking Server' },
  { pattern: 'parkpage.foundationapi.com', provider: 'Network Solutions parking' },
  { pattern: 'fabulous.com', provider: 'Fabulous' },
  { pattern: 'domainmarket.com', provider: 'DomainMarket' },
  { pattern: 'hugedomains.com', provider: 'HugeDomains' },
  { pattern: 'buydomains.com', provider: 'BuyDomains' },
  { pattern: 'parkingpage.namecheap.com', provider: 'Namecheap parking' },
  { pattern: 'registrar-servers.com.park', provider: 'Namecheap parking' },
  { pattern: 'sav.com', provider: 'Sav' },
  { pattern: 'brainydns.com', provider: 'Brainy DNS parking' },
  { pattern: 'nsone.net.parked', provider: 'NS1 parked' },
];

/**
 * The parking operator this zone is delegated to, where it is delegated to one.
 *
 * Suffix matching, like every other hostname table, and it was the one table doing something else:
 * the site collector tested `ns.includes(pattern)`, which asks whether the pattern appears anywhere
 * in the string rather than whether the nameserver sits under it. That is a real false positive on
 * the heaviest penalty the site dimension can apply. `dan.com` is a substring of `jordan.com`,
 * `sudan.com` and `bogdan.com`, and `above.com` is a substring of `above.community`, so a legitimate
 * domain delegated to `ns1.jordan.com` was parked at -12, flagged `parked`, and eligible for the
 * further -8 of `combo.parked_with_mx` if it also had mail.
 *
 * Three entries here end in `.parked` or `.park` and so match nothing under either rule, because no
 * such nameserver exists. They read as entries deliberately neutralised rather than deleted — the
 * bare forms `domaincontrol.com`, `registrar-servers.com` and `nsone.net` are each an operator's
 * ordinary delegation, and matching those would park every domain at GoDaddy, Namecheap and NS1.
 * Left exactly as they were: the change here is the matching rule, not the table.
 *
 * Lives beside the table rather than in the collector so the data module owns its own matcher, which
 * is the convention every other table in this directory already follows.
 */
export function matchParkingNameserver(
  nameservers: readonly string[] | undefined,
): { pattern: string; provider: string } | undefined {
  for (const ns of nameservers ?? []) {
    const match = PARKING_NAMESERVERS.find(({ pattern }) => isAtOrUnder(ns, pattern));
    if (match) return match;
  }
  return undefined;
}

/**
 * Phrases that name what the whole page is, used when the nameservers are inconclusive. Matched
 * case-insensitively against the fetched HTML.
 *
 * Every entry here is a sentence no working site has a reason to print. A page saying "domain default
 * page" or "account suspended" is not a site that mentions those things, it is a placeholder, and the
 * fingerprint is as good as the delegation evidence above it.
 *
 * `PLACEHOLDER_PHRASES` below holds the ones where that is not true, and the split matters: both lists
 * were one list, and the loose half was charging -12 to pages that were plainly working sites.
 */
export const PARKING_BODY_FINGERPRINTS: readonly string[] = [
  'this domain is for sale',
  'this domain name is for sale',
  'buy this domain',
  'domain is parked',
  'parked free, courtesy of',
  'the domain you are looking for is for sale',
  'inquire about this domain',
  'this webpage was generated by the domain owner using sedo',
  'sedo domain parking',
  'parkingcrew',
  'future home of something quite cool',
  'default web site page',
  'welcome to nginx',
  'apache2 ubuntu default page',
  'domain default page',
  /*
   * Five phrases found by reading the titles of every stored page the model did *not* call parked, which
   * is a question the fingerprint list had never been asked. They were the first and second most common
   * titles in that set: 121 pages titled "Parked Domain name on Hostinger DNS system" and 90 titled some
   * variant of "Parking Page". Both are pages declaring themselves parked in almost those words, and
   * neither matched anything above — `hostinger parking` was written for a page Hostinger does not serve,
   * and `domain is parked` does not occur in "Parked Domain name on".
   *
   * The cost of the miss was not the -12 alone. Those pages run to about 925 characters of boilerplate,
   * which cleared the 500-character substantive bar, so 129 of the 130 Hostinger pages were being *paid*
   * +6 for having a real website while the penalty for being a placeholder went unapplied.
   *
   * Every candidate was tested against all 133 legitimate pages in the holdout before being added here,
   * and that test is what kept the list honest: a bare `default page` drew 19 legitimate hits and was
   * dropped, and `web server is down` and `bad gateway` were dropped for a different reason — an origin
   * that is temporarily unreachable is not a parked domain, and reading a transient failure as evidence
   * of account farming is exactly what the "penalise only on positive evidence" rule forbids.
   *
   * `parking page` draws a single legitimate hit, `servicekee.net`, and it is kept anyway because that
   * page is titled "Namecheap Parking Page" and genuinely is one. The holdout label describes who
   * registered a domain, not what its web server is serving today.
   */
  'parked domain name',
  'parking page',
  'domain is expired',
  'domain has expired',
  'site not found',
  'this site is temporarily unavailable',
  'account suspended',
  'suspended page',
  'plesk default page',
  'cpanel default page',
  'hostinger parking',
  'this domain has been registered',
  /*
   * Squarespace's parking bundle, which it serves on a domain registered through it that has no site
   * attached. Matched on the asset path rather than the visible wording because the wording is
   * localised: this was found on a domain titled 近日中に公開, which the `coming soon` phrase misses
   * while the three English-language siblings beside it in the holdout were caught. Every fingerprint
   * in this list that is an English phrase has the same blind spot; an asset path does not.
   */
  'scripts-compressed/parking-page',
  /*
   * Language-independent parking bundles. English slogans miss localised pages; these are asset
   * paths and hostnames the parking operator's own HTML loads, so they survive translation.
   */
  'img.sedoparking.com',
  'sedoparking.com/registrar',
  'js.parkingcrew.net',
  'track.parkingcrew.net',
  'parkingcrew.net/js',
  'parkingpage.namecheap.com',
  'static.hugedomains.com',
  'img.afternic.com',
  'forsale.godaddy.com',
];

/**
 * Phrases that could just as easily be a line of copy on a working site, so they establish parking
 * only on a page that has nothing else on it.
 *
 * These sat in the list above and were charged the full -12, plus the further -8 of
 * `combo.parked_with_mx`, on the strength of a substring appearing anywhere in the HTML. "Coming soon"
 * is a label on an events listing, "make an offer" is a button on a shop, "index of /" is a line in
 * documentation, and "domain for sale" is the business a registrar is in. The result was that the
 * model asserted two contradictory things about one page: `site.substantive_content` paid +6 for a
 * page with real readable content while `site.parked` charged -12 for the same page being a
 * placeholder. Twelve holdout domains were in that state. Five were working sites belonging to real
 * organisations — a Chilean university, a Nigerian retail platform, an arts nonprofit in Duluth, a
 * renewable-energy firm, and Namecheap, which matched because selling domains is its business.
 *
 * So the rule is not that these phrases are worthless; `coming soon` alone appears on 29 abuse domains
 * in the holdout. It is that a phrase which only *suggests* a placeholder is answered by the page
 * itself. Where there is a title and five hundred characters of readable text, the page is not a
 * placeholder whatever one of its sentences says, and the three genuine parking pages that cleared
 * that bar in the holdout all matched `domain default page` above and are unaffected.
 *
 * Nameserver delegation and redirect-to-parking are untouched by any of this. Those are statements
 * made by the infrastructure rather than inferences from prose, and a parking service can serve
 * whatever page it likes without changing what it is.
 */
export const PLACEHOLDER_PHRASES: readonly string[] = [
  'make an offer',
  'domain for sale',
  'coming soon',
  'website coming soon',
  'under construction',
  'it works!',
  'index of /',
  /*
   * The same two sentences in other languages, which is the blind spot the asset-path entries in the
   * dispositive table above were added to work around. That note says every English phrase in these
   * lists misses a localised page; translating the two loosest phrases is the direct remedy, and it is
   * cheap because the gate above has already decided these only apply to a page with nothing on it.
   *
   * Restricted to wording that means "under construction" or "coming soon" and nothing else. Anything
   * looser would be guessing in a language the next reader may not be able to check, and the weak table
   * is the wrong place to take that risk even though its consequences are bounded.
   *
   * Spanish is matched on the stem because the word carries an accent that pages encode inconsistently,
   * and the only legitimate page in the holdout containing it is a 252,000-character Chilean university
   * site, which the substantive gate excludes before this list is ever consulted. That is the gate
   * earning its keep rather than a near miss.
   */
  'en construction',
  'en construcci',
  'em constru',
  'in costruzione',
  'im aufbau',
  'strona w budowie',
  'em breve',
  'proximamente',
];
